In [1]:
# ===========================================================
# F1M1 — Módulo 1: EDA Leonali
# Notebook 05 — KPIs automatizados con funciones reutilizables
# ===========================================================

import pandas as pd
import sys
sys.path.insert(0, '..')

from src.kpis import ticket_promedio, share_por_categoria, pareto_80_20, cliente_activos

In [2]:
df = pd.read_parquet('../data/processed/Dataset1_anonimizado.parquet')

In [4]:
ticket_promedio(df)

1249.434

In [5]:
share_por_categoria(df)

           Categoria1   Costo_Venta      share
0           Abarrotes  5.424110e+07   1.713439
1           Adicional  7.951782e+06   0.251191
2              Botana  8.240417e+08  26.030912
3            Ensalada  4.723796e+08  14.922148
4            Espinaca  1.125636e+09  35.558062
5   Espinaca Organica  3.304072e+07   1.043734
6              Fresco  2.496064e+07   0.788489
7               Hojas  6.001443e+08  18.958148
8               Jugos  4.078217e+06   0.128828
9           Smoothies  1.169118e+07   0.369316
10              Sopas  7.462382e+06   0.235732

In [6]:
pareto_80_20(df)

                    Producto   Costo_Venta   acumulado  es_80
92       Espinaca Baby 250gr  5.974864e+08   18.874186   True
87            Espinaca 200gr  1.624579e+08   24.006120   True
76        Ens Oriental 300gr  1.591741e+08   29.034322   True
137  Mks Espinaca Baby 250gr  1.458973e+08   33.643119   True
193     Zanahoria Baby 150gr  1.258905e+08   37.619915   True
..                       ...           ...         ...    ...
28               Betabel 1Kg  0.000000e+00  100.000000  False
8                 Ade Eneldo  0.000000e+00  100.000000  False
3          A Granel Kale 1Kg  0.000000e+00  100.000000  False
2        A Granel Acelga 1Kg  0.000000e+00  100.000000  False
107               Jicama 1Kg  0.000000e+00  100.000000  False

[214 rows x 4 columns]

In [3]:
cliente_activos(df)

    FechaProceso  IdCliente
0           2012         21
1           2013         28
2           2014         33
3           2015         43
4           2016         59
5           2017         60
6           2018         62
7           2019         82
8           2020         86
9           2021         77
10          2022         78

### Ticket Promedio
Mediana del costo de venta por transacción.

In [ ]:
ticket_promedio(df)

### Share por categoria
Muestra la participacion de cada categoria dentro de las ventas

In [ ]:
share_por_categoria(df)

In [ ]:
### Pareto 80-20
Calcula el 20% de los productos que hacen el 80% de las ventas

In [ ]:
pareto_80_20(df)

### Clientes activos
Cuenta el numero de clientes activos por año

In [ ]:
cliente_activos(df)